debug: false

ender_dragon:
  dropped_exp: 200

hotfix:
  reset_invulnerable_on_join: true

network_filter:
  # 是否启用?
  enabled: true
  # 进入挂机状态后定时给予经验球.
  idling_experience:
    # 经验球拥有的经验值. 每次只会创建一个经验球.
    # 设置为0时将不产生经验球, 定时任务也不会执行.
    amount: 1
    # 产生经验球的间隔
    # 单位: tick
    interval: 100
  # 进入挂机状态后, 不过滤这些实体产生的网络数据包.
  ignored_entity_types:
    - FISHING_HOOK
  # 进入挂机状态后, 需要被过滤的网络数据包的类型.
  suppressed_packet_types:
    - ACTION_BAR
    - BLOCK_ACTION
    - BLOCK_BREAK_ANIMATION
    - BLOCK_ENTITY_DATA
    - BOSS_BAR
    - BUNDLE
    - COLLECT_ITEM
    - ENTITY_ANIMATION
    - ENTITY_EQUIPMENT
    - ENTITY_HEAD_LOOK
    - ENTITY_METADATA
    - ENTITY_RELATIVE_MOVE
    - ENTITY_RELATIVE_MOVE_AND_ROTATION
    - ENTITY_ROTATION
    - ENTITY_SOUND_EFFECT
    - ENTITY_STATUS
    - HURT_ANIMATION
    - UPDATE_LIGHT
    - PARTICLE
    - SOUND_EFFECT
    - SPAWN_EXPERIENCE_ORB
    - TIME_UPDATE
    - UPDATE_ATTRIBUTES
    - UPDATE_LIGHT
    - VEHICLE_MOVE
